apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 1
  selector: 
    matchLabels: 
      components: backend
  template:
    metadata: 
      labels:
        components: backend
    spec: 
      containers:
        - name: conv-api
          image:  antonlarichev/conv-api:v1.0
          ports:
            - containerPort: 3000
          env:
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: SEED_USERNAME
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: SEED_USER_PASSWORD
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AMQP_HOSTNAME
          resources:
            limits:
              memory: "128Mi"
              cpu:  "500m"
          volumeMounts:
            - name: api-data
              mountPath: /opt/app/uploads
      volumes:
        - name: api-data
          persistentVolumeClaim:
            claimName: api-pvc