apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  AMQP_EXCHANGE: Y29udg==
  AMQP_HOSTNAME: cm1xLWNsdXN0ZXJpcA== 
  SEED_USERNAME: ZGVtbw==
  SEED_USER_PASSWORD: ZGVtbw==   
